limit_req_zone $binary_remote_addr zone=app_ip_limit:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=app_conn_limit:10m;

location / {
    limit_req zone=app_ip_limit burst=20 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/app/auth/entry.lua;

    proxy_pass 127.0.0.1:8080;
}