location ^~ /users/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /visitor-verification-reports/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /reservations/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /places/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /offers/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /location-check-ins/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /firebase/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /analysis/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /coupons/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /events/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /scout-field-reports/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /popup-campaigns/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /payments/ {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit 30;

    access_by_lua_file /src/lua/app_entry.lua;

    proxy_pass http://127.0.0.1:8080;
}
