worker_processes 1;
error_log logs/error.log info;
pid logs/nginx.pid;
env HMAC_SECRET_KEY;
env APP_HMAC_ENFORCE;
env WEB_GUARD_LIB;
env RUST_VALIDATOR_LIB;
env JWT_SECRET_KEY;
env BACKEND_HOST;
env BACKEND_PORT;
env REDIS_HOST;
env REDIS_PORT;
env AI_API_KEY;
env APP_HMAC_ENFORCE;

events {
    worker_connections 1024;
}

http {
    lua_package_path "/src/?.lua;/src/?/init.lua;;";

    include configs/conf.d/http/logging.conf;
    include configs/conf.d/http/ratelimit.conf;
    include configs/conf.d/http/openapi_forwarded.conf;
    
    server {
        listen 8081;
        server_name reverse_proxy;

        include configs/conf.d/web/locations.conf;
        include configs/conf.d/app/locations.conf;
        include configs/conf.d/shared/mysterio.conf;
        include configs/conf.d/app/ai.conf;
        
    }
}
