worker_processes 1;
daemon off;
error_log logs/error.log info;
pid logs/nginx.pid;
env HMAC_SECRET_KEY;
env SECRET_KEY;

events {
    worker_connections 1024;
}

http {
    lua_package_path "/src/?.lua;/src/?/init.lua;;";

    include configs/conf.d/http/logging.conf;
    include configs/conf.d/http/ratelimit.conf;
    
    server {
        listen 8081;
        server_name reverse_proxy;

        proxy_set_header Host $host;
        
        include configs/conf.d/shared/proxy_header.conf;
        include configs/conf.d/web/locations.conf;
        include configs/conf.d/app/locations.conf;
        
    }
}
