location / {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{id} {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-owner-profile {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{id}/submit {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{id}/reopen {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{id}/cancel {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{applicationId}/attachments {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{applicationId}/attachments/reorder {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

location ^~ /users/me/merchant-place-applications/{applicationId}/attachments/{attachmentId} {
    limit_req zone=app_ip_limit burst=40 nodelay;
    limit_conn app_conn_limit=30;

    access_by_lua_file /src/web/auth/entry.lua;

    proxy_pass http://127.0.0.1:8080;
}

