location = /swagger-ui {
    absolute_redirect off;
    return 301 /swagger-ui/;
}

location = /swagger-ui/ {
    include configs/conf.d/shared/proxy_header.conf;
    include configs/conf.d/shared/openapi_proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT/swagger-ui/index.html;
}

location = /swagger-ui.html {
    include configs/conf.d/shared/proxy_header.conf;
    include configs/conf.d/shared/openapi_proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location ^~ /swagger-ui/ {
    include configs/conf.d/shared/proxy_header.conf;
    include configs/conf.d/shared/openapi_proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location = /v3/api-docs {
    include configs/conf.d/shared/proxy_header.conf;
    include configs/conf.d/shared/openapi_proxy_header.conf;
    proxy_buffering off;
    proxy_redirect off;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location ^~ /v3/api-docs/ {
    include configs/conf.d/shared/proxy_header.conf;
    include configs/conf.d/shared/openapi_proxy_header.conf;
    proxy_buffering off;
    proxy_redirect off;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location = /favicon.ico {
    include configs/conf.d/shared/proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location ^~ /auth/ {
    include configs/conf.d/shared/proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location = /actuator/health {
    include configs/conf.d/shared/proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}

location / {
    limit_req zone=web_ip_limit burst=40 nodelay;
    limit_conn web_conn_limit 30;
    access_by_lua_file /src/lua/web_entry.lua;
    include configs/conf.d/shared/proxy_header.conf;
    proxy_pass http://BACKEND_HOST:BACKEND_PORT;
}
