worker_processes auto;
daemon off;
error_log logs/error.log warn;

env 

events {
    worker_connections 1024;
}

http {

    resolver 8.8.8.8;

    include       mime.types;
    default_type  application/octet-stream;

    lua_package_path "/usr/local/openresty/nginx/src/?.lua;/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/lualib/?.lua;;";

    header_filter_by_lua_block {
        -- 기존 Server 헤더(nginx/1.x.x)를 아예 삭제
        ngx.header.server = "clash.kr"
    
        -- 혹시 백엔드에서 보낸 다른 정체성 정보들도 삭제
        ngx.header["X-Powered-By"] = nil
        ngx.header["X-AspNet-Version"] = nil
    }

    include conf.d/*.conf;

    sendfile        on;
    keepalive_timeout  65;

    upstream backend {
        backend "pingdom.com:443";
    }

    #임시로 ssl 인증서 부분은 바이브 코딩으로 채움
    lua_shared_dict auto_ssl 1m;
    lua_shared_dict auto_ssl_settings 64k;

    init_by_lua_file src/init.lua

    init_worker_by_lua_file src/init_worker.lua

    server {
        listen 80;

        location /.well-known/acme-challenge/ {
            content_by_lua_block {
                require("resty.acme.autossl").serve_http_challenge()
            }
        }

        # 나머지 80 → 443 리다이렉트
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        
        # Dockerfile에서 만든 임시 인증서 경로와 일치해야 함
        ssl_certificate /etc/resty-auto-ssl/fallback.crt;
        ssl_certificate_key /etc/resty-auto-ssl/fallback.key;

        ssl_certificate_by_lua_block {
            auto_ssl:ssl_certificate()
        }

        # 사이퍼 방식이 더 안전한 조합으로만 허용하여 구형 브라우저의 취약점 차단, CPU 부하도 줄임
        ssl_protocols TLSv1.2 TLSv1.3; # 구형 브라우저 보안 취약점 차단
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers on;

        # OCSP Stapling: 인증서 유효성을 서버가 대신 확인해서 브라우저 속도 향상
        ssl_stapling on;
        ssl_stapling_verify on;
    }
}